### ISSUE TITLE
Docker install error 

### ISSUE THREAD

**Issue by sujitrp** [FloSchl8/openhab-ecovacs#2]
Hi ,
This really nice work. Enabling deebot with openhab . Surely this should go as binding in OH3 . 
For now, I am trying for Docker but getting the following error.
It will great to get help from u to resolve this. 

docker-compose.yml

`version: '3.4'

services:
  openhabdeebot:
    image: openhabdeebot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: openhabdeebot
    environment:
      - email=XXXXXX@gmail.com
      - password=XXXXXXXX
      - device_id=deebot950home
      - country=in
      - continent=as
      - verify_ssl=true
      - mqtt_client_id=deebot950
      - mqtt_client_host=XX.XX.XX.XX0
      - mqtt_client_port=1883
      - mqtt_client_username=XXXXX
      - mqtt_client_password=XXXXX
      - mqtt_client_keepalive=60
      - mqtt_client_root_topic=deebot950`
---------------------------------------------------
`
pi@PI99:~/openhab-ecovacs $ sudo docker-compose up -d
Creating network "openhab-ecovacs_default" with the default driver
Building openhabdeebot
Step 1/10 : FROM python:3.8-slim-buster
3.8-slim-buster: Pulling from library/python
c06905228d4f: Pull complete
576e27635e2a: Pull complete
31b618766132: Pull complete
ab17eeea6058: Pull complete
aa21e0c66711: Pull complete
Digest: sha256:cede59c0e2fcbabed9b3094f1564917632ecdd11c25c2a275654946938225ef4
Status: Downloaded newer image for python:3.8-slim-buster
 ---> 46f7808bb4f3
Step 2/10 : ENV PYTHONDONTWRITEBYTECODE=1
 ---> Running in 4c66b9c9146f
Removing intermediate container 4c66b9c9146f
 ---> 506ddcdcb369
Step 3/10 : ENV PYTHONUNBUFFERED=1
 ---> Running in 6aecbbb04c16
Removing intermediate container 6aecbbb04c16
 ---> c7d27e6d4fc3
Step 4/10 : ADD requirements.txt .
 ---> 3b5633dc4af7
Step 5/10 : RUN python -m pip install -r requirements.txt
 ---> Running in b69a7c2a81f5
Collecting attrs==20.3.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting certifi==2020.12.5
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click==7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting coverage==5.3
  Downloading coverage-5.3.tar.gz (693 kB)
Collecting deebotozmo==1.7.2
  Downloading deebotozmo-1.7.2.tar.gz (20 kB)
Collecting idna==2.10
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting iniconfig==1.1.1
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting numpy==1.19.4
  Downloading numpy-1.19.4.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: still running...
    Preparing wheel metadata: still running...
    Preparing wheel metadata: still running...
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnhmgrap2
         cwd: /tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92
    Complete output (227 lines):
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_common.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    /tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/system_info.py:1914: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    /tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE

    /tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE

    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    /tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    /tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    numpy_linalg_lapack_lite:
      FOUND:
        language = c

    /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.linux-armv7l-3.8
    creating build/src.linux-armv7l-3.8/numpy
    creating build/src.linux-armv7l-3.8/numpy/distutils
    building library "npymath" sources
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable nvfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-2ipe2geo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-2ipe2geo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 248, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-2ipe2geo/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 500, in setup_package
        setup(**metadata)
      File "/tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/tmp/pip-build-env-2ipe2geo/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-2ipe2geo/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/command/egg_info.py", line 24, in run
        self.run_command("build_src")
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/command/build_src.py", line 144, in run
        self.build_sources()
      File "/tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/command/build_src.py", line 155, in build_sources
        self.build_library_sources(*libname_info)
      File "/tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/command/build_src.py", line 288, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/tmp/pip-install-lulvnfj3/numpy_d5ebb2816da8407899bd2db3b59dae92/numpy/distutils/command/build_src.py", line 378, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 663, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnhmgrap2 Check the logs for full command output.
ERROR: Service 'openhabdeebot' failed to build: The command '/bin/sh -c python -m pip install -r requirements.txt' returned a non-zero code: 1

`

**Comment by FloSchl8** [comment]
Hi,

thanks. I'm currently getting familiar with Java, so who knows ;)

I've found similiar issues reasoning in an alpine base image.
(See issue in the SciPy repo: [SciPy #9481](https://github.com/scipy/scipy/issues/9481).
So I belive there are some issues with the base image here also.

Can you change the base image to `FROM python:3.8-buster` and try again pls?

Thanks

**Comment by sujitrp** [comment]
Hi Updating docker to python:3.8 Buster worked for me. Now Container is up and running. 

Portainer is showing a healthy status for container. 

Successfully built 9e1c1c828f19
Successfully tagged openhabdeebot:latest

Now the next question for me is How to get a device ID  ?

To retrieve this ID the easiest way is to start the library and watch the output.
How to start the library and watch the output?

**Comment by sujitrp** [comment]
Hi Checked Portainer log and found the device ID .  It is working like a charm . With buster it took 40 min on pi 4 to build the container.  Rebuild is not taking the time. 
Just one correction : 
for my ecovacs  topic set like    --  deebot950/<Device ID>/command  

deebot950/<Device ID>/battery_level
deebot950/<Device ID>/command
deebot950/<Device ID>/components/brush
deebot950/<Device ID>/components/heap
deebot950/<Device ID>/components/sideBrush
deebot950/<Device ID>/fanspeed
deebot950/<Device ID>/last_clean_image
deebot950/<Device ID>/mop_attached
deebot950/<Device ID>/stats_area
deebot950/<Device ID>/stats_cid
deebot950/<Device ID>/stats_time
deebot950/<Device ID>/stats_type
deebot950/<Device ID>/status
deebot950/<Device ID>/water_level

**Comment by FloSchl8** [comment]
Nice to hear that you got it working.
I think I have to adjust the readme a bit.

Sorry what do you mean?

**Comment by sujitrp** [comment]
read me says topic: for my ecovacs topic set like -- ecovacs /device ID /command 
but for my setup, the topic is like -- deebot950/device ID/command.

again little change is read me. 
Going forward:  
Get rooms and clean specific rooms feature will be nice.
